"""initial_schema_all_tables

Revision ID: f52289d1d84b
Revises: 
Create Date: 2026-09-12 14:11:49.999782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52289d1d84b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_role', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=150), nullable=True),
    sa.Column('related_circular_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_related_circular_id'), 'audit_logs', ['related_circular_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('recipients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_department'), 'recipients', ['department'], unique=False)
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_index(op.f('ix_recipients_name'), 'recipients', ['name'], unique=False)
    op.create_table('circulars',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ref_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('published_date', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('signatory', sa.String(length=150), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=50), nullable=True),
    sa.Column('supersedes_ref', sa.String(length=50), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=50), nullable=True),
    sa.Column('superseded_by_ref', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('required_actions', sa.JSON(), nullable=True),
    sa.Column('acknowledgement_rate', sa.Float(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('acknowledged_recipients', sa.Integer(), nullable=True),
    sa.Column('file_attachment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['circulars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['circulars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circulars_category'), 'circulars', ['category'], unique=False)
    op.create_index(op.f('ix_circulars_department'), 'circulars', ['department'], unique=False)
    op.create_index(op.f('ix_circulars_id'), 'circulars', ['id'], unique=False)
    op.create_index(op.f('ix_circulars_ref_no'), 'circulars', ['ref_no'], unique=True)
    op.create_index(op.f('ix_circulars_status'), 'circulars', ['status'], unique=False)
    op.create_index(op.f('ix_circulars_title'), 'circulars', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=True),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('can_upload_documents', sa.Boolean(), nullable=True),
    sa.Column('can_edit_documents', sa.Boolean(), nullable=True),
    sa.Column('can_approve_directives', sa.Boolean(), nullable=True),
    sa.Column('can_broadcast_nudge', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('acknowledgements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('circular_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('read_status', sa.String(length=50), nullable=True),
    sa.Column('acknowledgement_status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_at', sa.String(length=50), nullable=True),
    sa.Column('last_activity', sa.String(length=50), nullable=True),
    sa.Column('digital_signature_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acknowledgements_acknowledgement_status'), 'acknowledgements', ['acknowledgement_status'], unique=False)
    op.create_index(op.f('ix_acknowledgements_circular_id'), 'acknowledgements', ['circular_id'], unique=False)
    op.create_index(op.f('ix_acknowledgements_id'), 'acknowledgements', ['id'], unique=False)
    op.create_index(op.f('ix_acknowledgements_recipient_id'), 'acknowledgements', ['recipient_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('action_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_circular_id', sa.String(length=50), nullable=True),
    sa.Column('source_circular_ref', sa.String(length=50), nullable=True),
    sa.Column('responsible_role', sa.String(length=100), nullable=False),
    sa.Column('responsible_department', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_circular_id'], ['circulars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_id'), 'actions', ['action_id'], unique=True)
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_index(op.f('ix_actions_responsible_department'), 'actions', ['responsible_department'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('circular_versions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('circular_id', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('published_date', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circular_versions_circular_id'), 'circular_versions', ['circular_id'], unique=False)
    op.create_index(op.f('ix_circular_versions_id'), 'circular_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circular_versions_id'), table_name='circular_versions')
    op.drop_index(op.f('ix_circular_versions_circular_id'), table_name='circular_versions')
    op.drop_table('circular_versions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_responsible_department'), table_name='actions')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_acknowledgements_recipient_id'), table_name='acknowledgements')
    op.drop_index(op.f('ix_acknowledgements_id'), table_name='acknowledgements')
    op.drop_index(op.f('ix_acknowledgements_circular_id'), table_name='acknowledgements')
    op.drop_index(op.f('ix_acknowledgements_acknowledgement_status'), table_name='acknowledgements')
    op.drop_table('acknowledgements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_circulars_title'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_status'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_ref_no'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_id'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_department'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_category'), table_name='circulars')
    op.drop_table('circulars')
    op.drop_index(op.f('ix_recipients_name'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_department'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_related_circular_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
