from typing import List, Optional
from pydantic import BaseModel, Field


class AIChatRequest(BaseModel):
    message: str = Field(..., min_length=1, description="Question or prompt from user")


class AISource(BaseModel):
    document: str = Field(..., description="Source document filename")
    score: float = Field(..., description="Relevance similarity score (0.0 to 1.0)")
    chunk_id: Optional[str] = Field(None, description="Identifier of the chunk")


class AIChatResponse(BaseModel):
    answer: str = Field(..., description="Grounded response generated by Cira AI")
    sources: List[AISource] = Field(default_factory=list, description="Citations and referenced documents")
    is_grounded: bool = Field(True, description="Whether answer was derived from verified documents")
